### ISSUE TITLE
Adding custom data attributes to air-datepicker-cell

### ISSUE THREAD

**Issue by alexbogias** [t1m0n/air-datepicker#502]
Can you please add the option to add more data attributes to air-datepicker-cell element like data-year data-month etc. I need to add bootstrap 5 tooltip

**Comment by t1m0n** [comment]
Hello @alexbogias! You could use `onRenderCell` option to add custom html elements.

```javascript
new AirDatepicker('#el', {
  onRenderCell({ date, cellType }) {
    if (cellType === "day") {
      return {
        html: `<div data-custom-attribute='tooltip' class="air-datepicker--cell-inner">${date.getDate()}</div>`
      };
    }
  }
})
```

In this case add some custom styling to stretch inner content of the cells:

```css
.air-datepicker--cell-inner {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
}

```
