### ISSUE TITLE
My color scheme

### ISSUE THREAD

**Issue by DimNS** [t1m0n/air-datepicker#503]
And what about changing the color scheme of the calendar, how can I change the colors in the calendar without developing my own css file to replace?

**Comment by DimNS** [comment]
Here is my solution only 2 colors are used
```
accent: #e95420
hover: #c6471b
```

```css
/* #AirDatepicker color scheme */
.air-datepicker-cell.-selected-,
.air-datepicker-cell.-selected-.-current- {
    background: #e95420;
}

.air-datepicker-cell.-selected-.-focus- {
    background: #c6471b;
}

.air-datepicker-time--row input[type='range']:focus::-webkit-slider-thumb,
.air-datepicker-time--row input[type='range']:focus::-moz-range-thumb,
.air-datepicker-time--row input[type='range']:focus::-ms-thumb {
    background: #e95420;
    border-color: #e95420;
}

.air-datepicker-button,
.air-datepicker-cell.-current-,
.air-datepicker-cell.-current-.-in-range-,
.air-datepicker-body--day-name {
    color: #e95420;
}

.air-datepicker-body--day-name.-clickable-:hover {
    color: #c6471b;
}

.air-datepicker-cell.-in-range-,
.air-datepicker-cell.-range-from-,
.air-datepicker-cell.-range-to- {
    background-color: rgba(233, 84, 32, 0.1);
}

.air-datepicker-cell.-in-range-:hover {
    background-color: rgba(233, 84, 32, 0.2);
}

/* /AirDatepicker color scheme */
```

**Comment by t1m0n** [comment]
Hello @DimNS, you could change css variables to your prefer colors. CSS variables are located in https://github.com/t1m0n/air-datepicker/blob/v3/src/datepickerVars.scss. Just change any of that in your css file.

**my-colors.css**
```css
.air-datepicker {
 --adp-background-color-hover: gold;
}
```

**Comment by DimNS** [comment]
@t1m0n Are you talking about changing the values of variables and compiling a new final css file?

I want to do it on the fly, without compiling a new file

Here is for example how it is done in this plugin:
https://6edesign.github.io/svelte-calendar/docs/theme-editor/light

**Comment by t1m0n** [comment]
No, just add custom styles to your existing .css or .scss files. Simple example of how to change bg color - https://codesandbox.io/s/reverent-fast-gglczi?file=/src/styles.css

**Comment by DimNS** [comment]
I didn't think it was that simple, thank you

Here is an example with my colors:
```css
.air-datepicker {
    --adp-background-color-in-range: rgba(233, 84, 32, 0.1);
    --adp-background-color-in-range-focused: rgba(233, 84, 32, 0.2);
    --adp-background-color-selected-other-month-focused: #c6471b;
    --adp-background-color-selected-other-month: #e95420;
    --adp-accent-color: #e95420;
    --adp-color-current-date: var(--adp-accent-color);
    --adp-day-name-color: #e95420;
    --adp-day-name-color-hover: #c6471b;
    --adp-cell-background-color-selected: #e95420;
    --adp-cell-background-color-selected-hover: #c6471b;
    --adp-cell-background-color-in-range: rgba(233, 84, 32, 0.1);
    --adp-cell-background-color-in-range-hover: rgba(233, 84, 32, 0.2);
    --adp-cell-border-color-in-range: var(--adp-cell-background-color-selected);
    --adp-btn-color: var(--adp-accent-color);
}
```
