### ISSUE TITLE
Show only timepicker

### ISSUE THREAD

**Issue by dev4press** [t1m0n/air-datepicker#75]
Hi,

What is the best way to show and use timepicker only? This will show time controls only, and when time is selected, input field has only time, no date set.

Regards,
Milan

**Comment by t1m0n** [comment]
Hi! There is no default option for that, but you could hide unnecessary elements by `css`, and set `dateFormat` to one `space`, so only time will be set to input.
### HTML
```html
<input type="text" class="only-time"/>
```
### JS
```javascript
$('.only-time').datepicker({
    dateFormat: ' ',
    timepicker: true,
    classes: 'only-timepicker'
});
```
### CSS
```css
.only-timepicker .datepicker--nav,
.only-timepicker .datepicker--content {
    display: none;
}
.only-timepicker .datepicker--time {
    border-top: none;
}
```
